use anyhow::{bail, Context, Result};
use chrono::Utc;
use std::env;
use std::fs;
use std::path::PathBuf;
use telos_core::object::constraint::ConstraintSeverity;
use telos_core::hash::ObjectId;
use telos_store::query;
use telos_store::repository::Repository;

const MARKER_START: &str = "<!-- TELOS-CONSTRAINTS:START -->";
const MARKER_END: &str = "<!-- TELOS-CONSTRAINTS:END -->";

fn resolve_target_path(target: &str, output: &Option<String>, repo_root: &std::path::Path) -> Result<PathBuf> {
    match target {
        "claude" => Ok(repo_root.join("CLAUDE.md")),
        "codex" => Ok(repo_root.join("CODEX.md")),
        "generic" => {
            let name = output.as_deref().unwrap_or("AGENTS.md");
            Ok(repo_root.join(name))
        }
        _ => bail!("unknown target '{}' (expected: claude, codex, generic)", target),
    }
}

fn render_section(
    constraints: &[(ObjectId, telos_core::object::constraint::Constraint)],
    target: &str,
    timestamp: &str,
) -> String {
    let mut out = String::new();
    out.push_str(MARKER_START);
    out.push('\n');
    out.push_str(&format!(
        "<!-- generated by telos sync --target {} | {} | v1 -->\n",
        target, timestamp
    ));
    out.push('\n');
    out.push_str("## Project Constraints\n\n");
    out.push_str("> Auto-generated by `telos sync`. Do not edit manually.\n");
    out.push_str(&format!(
        "> Last synced: {} | Run `telos sync --target {}` to refresh.\n",
        timestamp, target
    ));

    // Group by severity
    let mut musts = Vec::new();
    let mut shoulds = Vec::new();
    let mut prefers = Vec::new();
    for (id, c) in constraints {
        let line = format_constraint_line(id, c);
        match c.severity {
            ConstraintSeverity::Must => musts.push(line),
            ConstraintSeverity::Should => shoulds.push(line),
            ConstraintSeverity::Prefer => prefers.push(line),
        }
    }

    if !musts.is_empty() {
        out.push_str("\n### Must\n\n");
        for line in &musts {
            out.push_str(line);
            out.push('\n');
        }
    }
    if !shoulds.is_empty() {
        out.push_str("\n### Should\n\n");
        for line in &shoulds {
            out.push_str(line);
            out.push('\n');
        }
    }
    if !prefers.is_empty() {
        out.push_str("\n### Prefer\n\n");
        for line in &prefers {
            out.push_str(line);
            out.push('\n');
        }
    }

    if target == "claude" || target == "codex" {
        out.push_str("\n---\n\n");
        out.push_str("Before modifying a file, query applicable constraints:\n");
        out.push_str("```\ntelos query constraints --file <path> --json\n```\n");
    }

    out.push('\n');
    out.push_str(MARKER_END);
    out
}

fn format_constraint_line(id: &ObjectId, c: &telos_core::object::constraint::Constraint) -> String {
    let mut line = format!("- {}", c.statement);
    if !c.impacts.is_empty() {
        line.push_str(&format!(" `[{}]`", c.impacts.join(", ")));
    }
    line.push_str(&format!(" `[id: {}]`", id.short()));
    line
}

fn splice_section(existing: &str, new_section: &str) -> String {
    if let (Some(start), Some(end)) = (existing.find(MARKER_START), existing.find(MARKER_END)) {
        let end = end + MARKER_END.len();
        let mut result = String::with_capacity(existing.len());
        result.push_str(&existing[..start]);
        result.push_str(new_section);
        result.push_str(&existing[end..]);
        result
    } else if existing.is_empty() {
        new_section.to_string()
    } else {
        let mut result = existing.to_string();
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result.push('\n');
        result.push_str(new_section);
        result.push('\n');
        result
    }
}

fn remove_section(existing: &str) -> String {
    if let (Some(start), Some(end)) = (existing.find(MARKER_START), existing.find(MARKER_END)) {
        let end = end + MARKER_END.len();
        let mut result = String::with_capacity(existing.len());
        let before = &existing[..start];
        let after = &existing[end..];

        // Trim trailing whitespace from before section
        let before = before.trim_end_matches('\n');
        result.push_str(before);

        // Trim leading whitespace from after section
        let after = after.trim_start_matches('\n');
        if !before.is_empty() && !after.is_empty() {
            result.push('\n');
            result.push('\n');
        }
        result.push_str(after);
        result
    } else {
        existing.to_string()
    }
}

pub fn run(
    target: String,
    output: Option<String>,
    only_must: bool,
    all: bool,
    dry_run: bool,
    remove: bool,
) -> Result<()> {
    let cwd = env::current_dir()?;
    let repo = Repository::discover(&cwd).context("not a Telos repository")?;
    let target_path = resolve_target_path(&target, &output, repo.root())?;

    // Handle --remove
    if remove {
        let existing = if target_path.exists() {
            fs::read_to_string(&target_path)?
        } else {
            println!("Nothing to remove (file does not exist)");
            return Ok(());
        };

        let cleaned = remove_section(&existing);
        if cleaned == existing {
            println!("No managed section found in {}", target_path.display());
            return Ok(());
        }

        if cleaned.trim().is_empty() {
            fs::remove_file(&target_path)?;
            println!("Removed managed section (file was empty, deleted {})", target_path.display());
        } else {
            atomic_write(&target_path, &cleaned)?;
            println!("Removed managed section from {}", target_path.display());
        }
        return Ok(());
    }

    // Load active constraints
    let constraints = query::query_constraints(&repo.odb, None, Some("active"))?;

    // Filter by severity
    let filtered: Vec<_> = constraints
        .into_iter()
        .filter(|(_, c)| {
            if only_must {
                c.severity == ConstraintSeverity::Must
            } else if all {
                true
            } else {
                // Default: Must + Should
                c.severity == ConstraintSeverity::Must || c.severity == ConstraintSeverity::Should
            }
        })
        .collect();

    if filtered.is_empty() {
        println!("No matching constraints to sync");
        return Ok(());
    }

    let timestamp = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();
    let section = render_section(&filtered, &target, &timestamp);

    if dry_run {
        println!("{}", section);
        println!("\n({} constraints would be synced to {})", filtered.len(), target_path.display());
        return Ok(());
    }

    let existing = if target_path.exists() {
        fs::read_to_string(&target_path)?
    } else {
        String::new()
    };

    let result = splice_section(&existing, &section);
    let action = if target_path.exists() { "Updated" } else { "Created" };

    atomic_write(&target_path, &result)?;
    println!(
        "{} {} with {} constraints",
        action,
        target_path.display(),
        filtered.len()
    );

    Ok(())
}

fn atomic_write(path: &PathBuf, content: &str) -> Result<()> {
    let dir = path.parent().context("invalid target path")?;
    let tmp = dir.join(format!(".telos-sync-{}.tmp", std::process::id()));
    fs::write(&tmp, content)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_into_empty_file() {
        let section = "<!-- TELOS-CONSTRAINTS:START -->\ntest\n<!-- TELOS-CONSTRAINTS:END -->";
        let result = splice_section("", section);
        assert_eq!(result, section);
    }

    #[test]
    fn splice_replaces_existing_section() {
        let existing = "# My Project\n\n<!-- TELOS-CONSTRAINTS:START -->\nold content\n<!-- TELOS-CONSTRAINTS:END -->\n\n## Notes";
        let new_section = "<!-- TELOS-CONSTRAINTS:START -->\nnew content\n<!-- TELOS-CONSTRAINTS:END -->";
        let result = splice_section(existing, new_section);
        assert!(result.contains("new content"));
        assert!(!result.contains("old content"));
        assert!(result.contains("# My Project"));
        assert!(result.contains("## Notes"));
    }

    #[test]
    fn splice_is_idempotent() {
        let existing = "# Header\n";
        let section = "<!-- TELOS-CONSTRAINTS:START -->\ncontent\n<!-- TELOS-CONSTRAINTS:END -->";

        let first = splice_section(existing, section);
        let second = splice_section(&first, section);
        assert_eq!(first, second);
    }

    #[test]
    fn splice_appends_to_existing_content() {
        let existing = "# My Project\n\nSome existing content.\n";
        let section = "<!-- TELOS-CONSTRAINTS:START -->\ntest\n<!-- TELOS-CONSTRAINTS:END -->";
        let result = splice_section(existing, section);
        assert!(result.starts_with("# My Project"));
        assert!(result.contains("Some existing content."));
        assert!(result.contains(MARKER_START));
        assert!(result.contains(MARKER_END));
    }

    #[test]
    fn remove_cleans_section() {
        let content = "# Header\n\n<!-- TELOS-CONSTRAINTS:START -->\nstuff\n<!-- TELOS-CONSTRAINTS:END -->\n\n## Footer";
        let result = remove_section(content);
        assert!(!result.contains(MARKER_START));
        assert!(!result.contains("stuff"));
        assert!(result.contains("# Header"));
        assert!(result.contains("## Footer"));
    }

    #[test]
    fn remove_noop_without_markers() {
        let content = "# Just a normal file\n\nNo markers here.\n";
        let result = remove_section(content);
        assert_eq!(result, content);
    }
}
